#!/bin/bash
timeToExpiry=$[ $(date --date=$(jq -r .Credentials.Expiration ~/.aws/temp_creds.json)  +%s) - $(date +%s) ]
if [ $timeToExpiry -lt 300 ] ; then
    read -p "MFA TOKEN: " TOKEN
    aws sts get-session-token --serial-number 'arn:aws:iam::278348662807:mfa/karthikeya@hasura.io'  --token-code $TOKEN > ~/.aws/temp_creds.json
fi
export AWS_ACCESS_KEY_ID=$(jq -r .Credentials.AccessKeyId ~/.aws/temp_creds.json)
export AWS_SECRET_ACCESS_KEY=$(jq -r .Credentials.SecretAccessKey ~/.aws/temp_creds.json)
export AWS_SESSION_TOKEN=$(jq -r .Credentials.SessionToken ~/.aws/temp_creds.json)
aws $*
